name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        shell: bash
        run: |
          set -e
          cat /etc/os-release 
          sudo apt-get update >/dev/null
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq ncat
          curl -LOs "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"
          tar xf shellcheck-v0.8.0.linux.x86_64.tar.xz shellcheck-v0.8.0/shellcheck
          mv shellcheck-v0.8.0/shellcheck /usr/local/bin/
          shellcheck -V
      - name: Create scripts from snippets
        shell: bash
        run: |
          bash create_installer.sh
          bash create_update.sh
      - name: Release
        shell: bash
        run: |
          set
          ls -la