name: Release
on:
  push:
    # VERSION=$(date +%y%m).$(date +%d|sed s/^0//).$(date +%k%M|tr -d ' ')
    # git tag $VERSION -m $VERSION && git push --follow-tags
    tags:
      - "*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        shell: bash
        run: |
          set -e
          cat /etc/os-release 
          sudo apt-get update >/dev/null
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq ncat
          curl -LOs "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"
          tar xf shellcheck-v0.8.0.linux.x86_64.tar.xz shellcheck-v0.8.0/shellcheck
          sudo mv shellcheck-v0.8.0/shellcheck /usr/local/bin/
          shellcheck -V
      - name: Create scripts from snippets
        shell: bash
        run: |
          bash create_installer.sh
          bash create_update.sh
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            rportd-installer.sh
            rportd-update.sh