name: Test-Ubuntu
on:
  push:
    branches:
      - main
jobs:
  Test-ubuntu:
    uses: cloudradar-monitoring/rportd-installer/.github/workflows/Test_tpl.yaml@main
    with:
      distribution: ubuntu