name: Test-Bullseye
on: 
  push:
    branches:
      - main
jobs:
  Test-bullseye:
    uses: cloudradar-monitoring/rportd-installer/.github/workflows/Test_tpl.yaml@main
    with:
      distribution: bullseye