name: Test-Debian
on: 
  push:
    branches:
      - main
jobs:
  Test-debian:
    uses: cloudradar-monitoring/rportd-installer/.github/workflows/Test_tpl.yaml@main
    with:
      distribution: debian